### ISSUE TITLE
wmctrl crashes software before installation

### ISSUE THREAD

**Issue by TheOnion313** [cryinkfly/SOLIDWORKS-for-Linux#17]
I tried to run the installation but after installing the dependencies it suddenly stopped, so I looked into the code and found out that the program stops at line 69 which contains:
`    wmctrl -r ':ACTIVE:' -b toggle,fullscreen `

I don't know why but the wmctrl module didn't respond well with the system and terminated the program, once I uncommented it worked fine, and since it only switches to fullscreen, it probably isn't necessary.

**Comment by cryinkfly** [comment]
I change the setup wizard in the next time so that this works with zenity. :+1:
