### ISSUE TITLE
Not able to access dl-ak.solidworks.com

### ISSUE THREAD

**Issue by dmangal85** [cryinkfly/SOLIDWORKS-for-Linux#19]
Hi the script stops at 

Connecting to dl-ak.solidworks.com (dl-ak.solidworks.com)|2600:1405:e000:1a5::3144|:443...

Is there another link? Can i use my own .exe file to run instead?

**Comment by Duedot43** [comment]
Could you provide more verbose info on what happened before that error?

**Comment by dmangal85** [comment]
Here are a few more lines from the terminal window after the script hangs at downloading SW. 

0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0048:fixme:imm:ImeSetActiveContext (0x25ae30, 0): stub
0048:fixme:imm:ImmReleaseContext (0000000000010020, 000000000025AE30): stub
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\win32k.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgkrnl.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgmms1.sys"
002c:fixme:imm:ImeSetActiveContext (0x256d80, 1): stub
002c:fixme:imm:ImmReleaseContext (0000000000020056, 0000000000256D80): stub
0090:fixme:file:NtLockFile I/O completion on lock not implemented yet
0090:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:fixme:file:NtLockFile I/O completion on lock not implemented yet
0098:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0098:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
wine: configuration in L"/home/dmangal/.wineprefixes/solidworks" has been updated.
0114:fixme:file:NtLockFile I/O completion on lock not implemented yet
--2022-01-11 11:18:52--  https://dl-ak.solidworks.com/nonsecure/sw2020/sw2020_sp04.0_f/x64/200715.002-1-QA7UDVC9/SolidWorksSetup.exe
Resolving dl-ak.solidworks.com (dl-ak.solidworks.com)... 2600:1405:e000:1a7::3144, 2600:1405:e000:1a5::3144, 104.100.225.113
Connecting to dl-ak.solidworks.com (dl-ak.solidworks.com)|2600:1405:e000:1a7::3144|:443... failed: Connection timed out.
Connecting to dl-ak.solidworks.com (dl-ak.solidworks.com)|2600:1405:e000:1a5::3144|:443...

**Comment by Duedot43** [comment]
Have you tried running it again? It seems it's being a bit slow to connect have you also tried checking your network or clicking that link and seeing if it downloads from there?

**Comment by dmangal85** [comment]
Here are a few more lines from the terminal window after the script hangs at downloading SW. 

0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0048:fixme:imm:ImeSetActiveContext (0x25ae30, 0): stub
0048:fixme:imm:ImmReleaseContext (0000000000010020, 000000000025AE30): stub
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\win32k.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgkrnl.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgmms1.sys"
002c:fixme:imm:ImeSetActiveContext (0x256d80, 1): stub
002c:fixme:imm:ImmReleaseContext (0000000000020056, 0000000000256D80): stub
0090:fixme:file:NtLockFile I/O completion on lock not implemented yet
0090:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0090:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:fixme:file:NtLockFile I/O completion on lock not implemented yet
0098:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:err:mscoree:LoadLibraryShim error reading registry key for installroot
0098:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0098:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
wine: configuration in L"/home/dmangal/.wineprefixes/solidworks" has been updated.
0114:fixme:file:NtLockFile I/O completion on lock not implemented yet
--2022-01-11 11:18:52--  https://dl-ak.solidworks.com/nonsecure/sw2020/sw2020_sp04.0_f/x64/200715.002-1-QA7UDVC9/SolidWorksSetup.exe
Resolving dl-ak.solidworks.com (dl-ak.solidworks.com)... 2600:1405:e000:1a7::3144, 2600:1405:e000:1a5::3144, 104.100.225.113
Connecting to dl-ak.solidworks.com (dl-ak.solidworks.com)|2600:1405:e000:1a7::3144|:443... failed: Connection timed out.
Connecting to dl-ak.solidworks.com (dl-ak.solidworks.com)|2600:1405:e000:1a5::3144|:443...

**Comment by dmangal85** [comment]
You are right. it seems its just slow to load. But now I Am stuck on the installation screen. I will close this and post another issue. 

Thank you
