### ISSUE TITLE
No progress after language selection

### ISSUE THREAD

**Issue by Beeperz** [cryinkfly/SOLIDWORKS-for-Linux#31]
Please help! 
My system - Kubuntu 22.10 x64, freshly installed, no modifications.
No progress after language selection:

In this step you need to choose a language for the SOLIDWORKS installation!
Choose one of these options: (English(en), German(de) or Quit(q)en

**Comment by xxb1s** [comment]
@Beeperz The languages.sh have a problem, you can follow both sh files to know what message should be showed
Another error is in the install file, one function call is bad named
In the line 58 the function is `selectyouros` instead `select-your-os`

**Comment by Bizburger13** [comment]
Hi,
I have the same issue and I did not find the solution.
Any help Please ?

**Comment by nathaneltitane** [comment]
similar problem with your scripts - you also need to mention somewhere that languages.sh must be downloaded separately or add it to the code snipped you have on the github page...

after selecting language i ask it to install missing packages and the script exits with:
`solidworks-install.sh: line 56: install-requirement: command not found`

![image](https://user-images.githubusercontent.com/5674757/219902651-c900debb-c6b5-46b5-a04a-513df439093b.png)

**Comment by cryinkfly** [comment]
Please use the updated script!
