### ISSUE TITLE
cannot access 'solidworks-install.sh': No such file or directory *solved*

### ISSUE THREAD

**Issue by Amm009** [cryinkfly/SOLIDWORKS-for-Linux#42]
I barely know how to do basic coding so this might be something very simple, but this error pops up when I tried to run the command on the main page. I installed all of the packages that I could (the package manager said that it could not find winbind, p7zip-full, and p7zip-rar). Also the script releases link is broken, so if there is something in there that I need then I cannot access it. I have the installer for SolidWorks downloaded as well. This is what pops up when I try to run the command:

`cd ~/Downloads && wget -N https://raw.githubusercontent.com/cryinkfly/SOLIDWORKS-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x solidworks-install.sh && ./install.sh
--2023-06-02 21:48:50--  https://raw.githubusercontent.com/cryinkfly/SOLIDWORKS-for-Linux/main/files/builds/stable-branch/bin/install.sh
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27049 (26K) [text/plain]
Saving to: ‘install.sh’

install.sh                  100%[=========================================>]  26.42K  --.-KB/s    in 0.004s  

Last-modified header missing -- time-stamps turned off.
2023-06-02 21:48:50 (6.93 MB/s) - ‘install.sh’ saved [27049/27049]

chmod: cannot access 'solidworks-install.sh': No such file or directory
`
I'm guessing I should have solidworks-install.sh downloaded somewhere, but I don't know where to find it.

I feel like it should put that in a code format, but it's not doing that >:(

**Comment by Duedot43** [comment]
The README appears to not be updated replace `solidworks-install.sh` in your original command with `install.sh`

Also when Bash says "no such file or directory" that means as it says it cannot find the file your looking for so double check that you typed the name correctly and and that the file appears when you type `ls` (list) which lists the contents of the current directory also don't forget that directory and file names are caps sensitive!

**Comment by DeflateAwning** [comment]
This issue is fixed in PR #48
