### ISSUE TITLE
Support other SolidWorks versions *solved*

### ISSUE THREAD

**Issue by cewbdex** [cryinkfly/SOLIDWORKS-for-Linux#5]
I see there is an only option to use the 2020 version, sadly my university still has only 2019 license, would it be possible to add? Thanks.

**Comment by cryinkfly** [comment]
@cewbdex Yes you can! I get my serial number from here: https://www.mbcad.de/solidworks-produkte/solidworks-privatlizenz/ 

... but I have the problem with the installation of VBA 7.1 , what we need, when we will use this 2020 or newer version.

Can you check, which VBA version will be install SOLIDWORKS 2019 version, please?

**Comment by Dyllan2000alfa** [comment]
Did some testing / research and the VBA 7.1 issue seems to only be for solidworks 2020, both solidworks 2019 and 2021 use a different version that I had no problem installing through the installer. As a suggestion it would be nice to add a way to specify a different exe in the script for anyone using different versions, as well as making the VBA workaround for solidworks 2020 toggleable for versions that don't need it.

**Comment by cryinkfly** [comment]
I have found out that Dassault Systèmes have created "DEXPERIENCE SOLIDWORKS for Maker und Private users" that works with the internet browser!

Here is the link: https://discover.solidworks.com/makers

But it cost US$99.00/year!!!

---

@Dyllan2000alfa Can you give me a link from the installer of the version 2021 of SOLIDWORKS? Then I have only this link:

> https://dl-ak.solidworks.com/nonsecure/sw2020/sw2020_sp04.0_f/x64/200715.002-1-QA7UDVC9/SolidWorksSetup.exe

**Comment by Dyllan2000alfa** [comment]
@cryinkfly I cant give you a link since the link I use is a temporarily one that is created after I enter my schools license number. Do you think you could make it so people can manually specify an exe they have downloaded?

**Comment by dzervas** [comment]
I registered for an education trial [here](https://www.solidworks.com/support/community-download) with the code `TEMPDL` and got the latest exe link: https://dl-ak.solidworks.com/nonsecure/sw2022/sw2022_sp02.0_f/x64/220318.003-1-PGQH6ND3/SolidWorksSetup.exe

**Comment by dzervas** [comment]
Oh I forgot I already made a PR here https://github.com/cryinkfly/SOLIDWORKS-for-Linux/pull/22

**Comment by Beeperz** [comment]
> I registered for an education trial [here](https://www.solidworks.com/support/community-download) with the code `TEMPDL` and got the latest exe link: https://dl-ak.solidworks.com/nonsecure/sw2022/sw2022_sp02.0_f/x64/220318.003-1-PGQH6ND3/SolidWorksSetup.exe
> 
> The serial numbers are also static (they give the same to everyone) but I'm not sure if it's ok to share them (even a fake email will give you the serials)

Can you post download link to 2021 version? Thank you!

**Comment by dzervas** [comment]
> Can you post download link to 2021 version? Thank you!

[Here](https://dl-ak.solidworks.com/nonsecure/sw2021/sw2021_sp03.0_f/x64/210326.009-1-GDT1XGXA/SolidWorksSetup.exe ) you go :smiley:

**Comment by cryinkfly** [comment]
So, I have add an option in my new installer where the user can select another SOLIDWORK version which is downloaded in his home directory! :+1:

**Comment by mscipio** [comment]
I have been trying to install this package using, I believe, the latest version updated today, but I am not able to move forward with the installation after I reach the "Version Selection" screen.

I suppose option 1 is defaulted to SW 2022, and option 2 should let the user free to choose another option (I have an installer for 2019 Pro, for instance that I want to use), but the is no keyboard input that allows me to move forward and select the "OK" option ... is it me?
